Create View
Epaltechs/Blog-App pull request #8
Opened 2022-08-31 20:52 UTC by Epaltechs

### At this juncture in the project, I:
- Implement the design from the sneak peek wireframes. (https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/images/blog_root_users.png?raw=true)
- Use methods that were created in the processing data in models.
- Add some data to the database.

2022-08-31 21:40 UTC, KDlamini requested changes
### Hi @Epaltechs 🙋‍♀️,  

Great work so far! 💯 
You still need to work on some issues to improve your project according to the requirements. You are almost there! 💪🏾 

## Highlights 🌞 
✔️  Good PR tdescription
✔️  Correct use of Gitflow 
✔️  Commit messages are meaningful
✔️  No linter errors

## Required Changes ♻️
 
**Kindly look through the comments below 👇 for required changes**

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers 🥂  and Happy coding!!! 👯 
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @KDlamini  in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-31 21:40 UTC, KDlamini commented on db/migrate/20220831160429_create_articles.rb
> +      t.timestamps
When I try to populate the database with data to test your views I get an error, specifically with creating posts.

![Screenshot from 2022-08-31 23-22-30](https://user-images.githubusercontent.com/38088818/187788291-180a8c4c-64a6-43cb-b210-e5efe918bd8c.png)

This happens when I try to creating a post by running:
`first_post = Post.create(author: first_user, title: 'Hello', text: 'This is my first post')`

after creating users with;
```
   first_user = User.create(name: 'Tom', photo: 'https://unsplash.com/photos/F_-0BxGuVvo', bio: 'Teacher from Mexico.')
   second_user = User.create(name: 'Lilly', photo: 'https://unsplash.com/photos/F_-0BxGuVvo', bio: 'Teacher from Poland.')
```

and comments with:
`Comment.create(post: first_post, author: second_user, text: 'Hi Tom!' )`

If you are using a different format to insert data into your database, kindly create sample data in your `db/seed.rb` file which can be run to populate your database.

Please make sure that:

- There's at least one user
- At least 4 posts written by one of the users you created
- At least 6 posts comments for one of the posts you created

2022-09-01 14:52 UTC, Epaltechs commented
#### At this point, I create sample data in db/seed.rb file that can be run to populate the database, as requested by the code reviewer. Also, I have added a direction in the README file on how to run the code.

2022-09-01 14:58 UTC, DeliceLydia approved these changes
## Hi @Epaltechs 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
# Congratulations! 🎉 



### Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-01 14:59 UTC, merged